services:
    _defaults:
        autoconfigure: true
        autowire: true

    DeEs\ContaoGridContainer\:
        resource: ../src
        exclude: ../src/{ContaoManager,ContaoGridContainerBundle.php}
